name: 'Email Notification'
description: 'Sends email notification with workflow results'
inputs:
  recipient:
    description: 'Email recipient address'
    required: true
  linter_result:
    description: 'Linter job result'
    required: true
  cypress_result:
    description: 'Cypress job result'
    required: true
  badge_result:
    description: 'Badge job result'
    required: true
runs:
  using: 'node16'
  main: 'index.js'
