name: CI

on: [push, pull_request]

jobs:
  linter_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint


  cypress_job:
    runs-on: ubuntu-latest
    needs: linter_job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          start: npm run dev
          wait-on: http://localhost:3000
          wait-on-timeout: 60
          continue-on-error: true

      - name: Save Cypress results
        run: echo ${{ steps.run_tests.outcome }} > result.txt
        continue-on-error: true

      - name: Upload result artifact
        uses: actions/upload-artifact@v3
        with:
          name: cypress-results
          path: result.txt


  add_badge_job:
    runs-on: ubuntu-latest
    needs: cypress_job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Download Cypress results
        uses: actions/download-artifact@v3
        with:
          name: cypress-results
      - name: Generate output
        run: |
          echo "::set-output name=cypress_outcome::$(cat result.txt)"
      - name: Update README with badge
        uses: ./your-custom-action
        with:
          outcome: ${{ steps.generate_output.outputs.cypress_outcome }}
      - name: Commit and push changes
        run: |
          git config user.name "Javier Tomás Tormo - GitHub Actions"
          git config user.email "javtomtor@alu.edu.gva.es"
          git add README.md
          git commit -m "Update badge"
          git push
